import sys
from PyQt5.QtWidgets import *
class DailyInput(QWidget):
    def __init__(self):
        super().__init__()
        self._InitUI()
        pass
    def _InitUI(self):
        MainLayout = QVBoxLayout()

        group1 = QGroupBox(self.tr('Standar working hour'))
        group1Layout = QHBoxLayout()
        LbStd1 = QLabel(self.tr('Normal T'))
        lEdtNormalTime = QLineEdit(self.tr('8.0'))
        lEdtNormalTime.setReadOnly(1)
        LbStd2 = QLabel(self.tr('Over T'))
        lEdtOverTime = QLineEdit(self.tr('2.0'))
        lEdtOverTime.setReadOnly(1)
        group1Layout.addWidget(LbStd1)
        group1Layout.addWidget(lEdtNormalTime)
        group1Layout.addWidget(LbStd2)
        group1Layout.addWidget(lEdtOverTime)

        group2 = QGroupBox(self.tr('Currnet working choice'))
        group2Layout = QHBoxLayout()
        ChkNormal = QRadioButton(self.tr('Normal'))
        ChkNormal.setChecked(1)
        ChkOverTime = QRadioButton(self.tr('Over'))
        self.btnDutyOn = QPushButton(self.tr('DutyOn'))
        self.btnDutyOff = QPushButton(self.tr('DutyOff'))
        group2Layout.addWidget(ChkNormal)
        group2Layout.addWidget(ChkOverTime)
        group2Layout.addWidget(self.btnDutyOn)
        group2Layout.addWidget(self.btnDutyOff)

        group1.setLayout(group1Layout)
        group2.setLayout(group2Layout)

        headLayout = QHBoxLayout()
        headLayout.addWidget(group1)
        headLayout.addWidget(group2)

        bodyLayout = QGridLayout()
        group3 = QGroupBox(self.tr('Working infomation'))
        group3Layout = QVBoxLayout()
        tmpLayout1 = QHBoxLayout()
        lbWorkCell = QLabel(self.tr('workcell name:'))
        lbWorkCellName = QLabel(self.tr('tmp'))
        tmpLayout1.addWidget(lbWorkCell)
        tmpLayout1.addWidget(lbWorkCellName)
        tmpLayout2 = QHBoxLayout()
        lbserial = QLabel(self.tr('serial name:'))
        lbseriaNamel = QLabel(self.tr('tmp'))
        tmpLayout2.addWidget(lbserial)
        tmpLayout2.addWidget(lbseriaNamel)
        tmpLayout3 = QHBoxLayout()
        lbCycleTime_ = QLabel(self.tr('Cycle time:'))
        lbCycleTime = QLabel(self.tr('tmp'))
        tmpLayout3.addWidget(lbCycleTime_)
        tmpLayout3.addWidget(lbCycleTime)
        tmpLayout4 = QHBoxLayout()
        lbCylcleOutput_ = QLabel(self.tr('Cycle output:'))
        lbCylcleOutput = QLabel(self.tr('tmp'))
        tmpLayout4.addWidget(lbCylcleOutput_)
        tmpLayout4.addWidget(lbCylcleOutput)
        group3Layout.addLayout(tmpLayout1)
        group3Layout.addLayout(tmpLayout2)
        group3Layout.addLayout(tmpLayout3)
        group3Layout.addLayout(tmpLayout4)
        group3.setLayout(group3Layout)

        group4 = QGroupBox(self.tr('Working Setting'))
        group4Layout = QVBoxLayout()
        tmpLayout5 = QHBoxLayout()
        lbPartNum = QLabel(self.tr('Pn:'))
        lEditPartNum = QLineEdit(self.tr('0560 1012'))
        tmpLayout5.addWidget(lbPartNum)
        tmpLayout5.addWidget(lEditPartNum)
        tmpLayout6 = QHBoxLayout()
        lbDate = QLabel(self.tr('Date:'))
        DateEdt = QDateEdit();
        tmpLayout6.addWidget(lbDate)
        tmpLayout6.addWidget(DateEdt)
        tmpLayout7 = QHBoxLayout()
        lbRealTime = QLabel(self.tr('RealTime:'))
        lEditRealTime = QLineEdit(self.tr('80.2'))
        tmpLayout7.addWidget(lbRealTime)
        tmpLayout7.addWidget(lEditRealTime)
        tmpLayout8 = QHBoxLayout()
        lbProdQty = QLabel(self.tr('Prod.Qty:'))
        lEditProdQty = QLineEdit(self.tr('16'))
        tmpLayout8.addWidget(lbProdQty)
        tmpLayout8.addWidget(lEditProdQty)
        tmpLayout9 = QHBoxLayout()
        lbProdPlan = QLabel(self.tr('Prod.Min:'))
        lEditProdPlan = QLineEdit(self.tr('90'))
        tmpLayout9.addWidget(lbProdPlan)
        tmpLayout9.addWidget(lEditProdPlan)
        tmpLayout10 = QHBoxLayout()
        lbOperatorID = QLabel(self.tr('Operator ID:'))
        lEditOperatorID = QLineEdit(self.tr('1029'))
        tmpLayout10.addWidget(lbOperatorID)
        tmpLayout10.addWidget(lEditOperatorID)

        ChkIfRework = QCheckBox(self.tr('ReworkOrAccessory'))
        btnOk = QPushButton(self.tr('OK'))
        group4Layout.addLayout(tmpLayout5)
        group4Layout.addLayout(tmpLayout6)
        group4Layout.addLayout(tmpLayout7)
        group4Layout.addLayout(tmpLayout8)
        group4Layout.addLayout(tmpLayout9)
        group4Layout.addLayout(tmpLayout10)
        group4Layout.addWidget(ChkIfRework)
        group4Layout.addWidget(btnOk)
        group4.setLayout(group4Layout)

        group5 = QGroupBox(self.tr('Metrial and Equitment'))
        group5Layout = QVBoxLayout()
        tmpLayoutV1 = QHBoxLayout()
        lbID = QLabel(self.tr('1.'))
        lEdtStepDescripe = QLineEdit()
        lEdtTime = QLineEdit()
        lEdtType = QLineEdit()
        lEdtafectTime = QLineEdit()
        cmbReason = QComboBox()
        lEdtBrokenSum = QLineEdit()
        lEdtBrokenStep = QLineEdit()
        tmpLayoutV1.addWidget(lbID)
        tmpLayoutV1.addWidget(lEdtStepDescripe)
        tmpLayoutV1.addWidget(lEdtTime)
        tmpLayoutV1.addWidget(lEdtType)
        tmpLayoutV1.addWidget(lEdtafectTime)
        tmpLayoutV1.addWidget(cmbReason)
        tmpLayoutV1.addWidget(lEdtBrokenSum)
        tmpLayoutV1.addWidget(lEdtBrokenStep)
        tmpLayoutV2 = QHBoxLayout()
        lbID = QLabel(self.tr('2.'))
        lEdtStepDescripe = QLineEdit()
        lEdtTime = QLineEdit()
        lEdtType = QLineEdit()
        lEdtafectTime = QLineEdit()
        cmbReason = QComboBox()
        lEdtBrokenSum = QLineEdit()
        lEdtBrokenStep = QLineEdit()
        tmpLayoutV2.addWidget(lbID)
        tmpLayoutV2.addWidget(lEdtStepDescripe)
        tmpLayoutV2.addWidget(lEdtTime)
        tmpLayoutV2.addWidget(lEdtType)
        tmpLayoutV2.addWidget(lEdtafectTime)
        tmpLayoutV2.addWidget(cmbReason)
        tmpLayoutV2.addWidget(lEdtBrokenSum)
        tmpLayoutV2.addWidget(lEdtBrokenStep)
        tmpLayoutV3 = QHBoxLayout()
        lbID = QLabel(self.tr('3.'))
        lEdtStepDescripe = QLineEdit()
        lEdtTime = QLineEdit()
        lEdtType = QLineEdit()
        lEdtafectTime = QLineEdit()
        cmbReason = QComboBox()
        lEdtBrokenSum = QLineEdit()
        lEdtBrokenStep = QLineEdit()
        tmpLayoutV3.addWidget(lbID)
        tmpLayoutV3.addWidget(lEdtStepDescripe)
        tmpLayoutV3.addWidget(lEdtTime)
        tmpLayoutV3.addWidget(lEdtType)
        tmpLayoutV3.addWidget(lEdtafectTime)
        tmpLayoutV3.addWidget(cmbReason)
        tmpLayoutV3.addWidget(lEdtBrokenSum)
        tmpLayoutV3.addWidget(lEdtBrokenStep)

        group5Layout.addLayout(tmpLayoutV1)
        group5Layout.addLayout(tmpLayoutV2)
        group5Layout.addLayout(tmpLayoutV3)
        group5.setLayout(group5Layout)

        bodyLayout.setColumnStretch(1, 1)
        bodyLayout.setColumnStretch(2, 9)
        bodyLayout.addWidget(group3,0,0)
        bodyLayout.addWidget(group5,0,1)
        bodyLayout.addWidget(group4,1,0)


        MainLayout.addLayout(headLayout)
        MainLayout.addLayout(bodyLayout)
        self.setLayout(MainLayout)
